"""What a strategy is, what it can see, and how its parameters are declared.

docs/plans/trading.md Phase 4: *"the ``Strategy`` protocol: a pydantic
``Params`` model declaring each tunable with its type, range and default, plus
``on_bar(ctx)``. The declared ranges are what Phase 5 sweeps."* Three things
follow from taking the second sentence literally.

**The range lives on the field, not in the sweep launcher.** ``swept()`` is an
ordinary pydantic ``Field`` carrying a low, a high and a step, so the range is
validated on every construction *and* readable as data by anything that wants
the parameter space - Phase 5's sweep, Phase 7's launcher, and the JSON schema
the UI renders. A range that lived in the launcher would be a second
declaration that can disagree with the model, and the disagreement would show
up as a sweep that spends an hour producing runs the model then rejects.

**The context is the entire surface a strategy has.** ``ctx.now``,
``ctx.bars()``, ``ctx.chain()``, ``ctx.portfolio`` - the plan names all four -
plus the two ways to place an order. There is deliberately no handle on the
clock, the history or the broker: those are the three objects through which a
strategy could see a bar it should not or fill on the bar it signalled from,
and the protection is that it is never given one. The lookahead gate is a test
(``tests/test_engine_lookahead.py``) and this is the design that lets the test
be short.

**A strategy is a plain object, constructed from validated params.** No base
class to inherit, no registration decorator with import-order semantics. It has
``on_bar`` and it has ``params``, and the module that defines it exports a
``StrategySpec`` naming it. Phase 7's seed job reads the specs; Phase 5's
worker builds from one. The ask's *"I would generally expect to have to develop
and deploy code to introduce a whole new strategy"* is exactly this: a class is
code and a deploy, a ``param_set`` is data.
"""

from __future__ import annotations

from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from typing import TYPE_CHECKING, Any, Protocol, cast, runtime_checkable

from pydantic import BaseModel, ConfigDict, Field
from pydantic.fields import FieldInfo

from aerie_trading.engine.broker import Broker, Order
from aerie_trading.engine.history import BarHistory
from aerie_trading.engine.instruments import Instrument
from aerie_trading.engine.money import money
from aerie_trading.engine.portfolio import Portfolio, position_key_for
from aerie_trading.providers.base import Bar

if TYPE_CHECKING:  # pragma: no cover - a type, not a dependency
    # Under `from __future__ import annotations` this never executes at
    # runtime, which is the point: `engine.strategy` is imported by every
    # process that builds a strategy, and polars is 40 MB that only
    # `engine.history` and the lake actually need.
    import polars as pl

__all__ = [
    "SWEEP_KEY",
    "Params",
    "Strategy",
    "StrategyContext",
    "StrategySpec",
    "SweepRange",
    "swept",
]

#: The key ``swept()`` writes into a field's ``json_schema_extra`` and
#: ``Params.sweep_space`` reads back out. A constant because the two halves are
#: read by different phases in different processes, and a typo in one of them
#: would read as a parameter that is simply not swept.
SWEEP_KEY = "sweep"


@dataclass(frozen=True, slots=True)
class SweepRange:
    """An inclusive range and a step, as declared on a parameter.

    Decimal rather than float throughout, because a step of ``0.1`` walked in
    binary arithmetic produces ``0.30000000000000004`` as a parameter value -
    which is a distinct ``param_set`` row from ``0.3``, and two sweeps over the
    same declared range would produce different sets of them depending on where
    they started.
    """

    low: Decimal
    high: Decimal
    step: Decimal
    description: str = ""

    def __post_init__(self) -> None:
        if self.step <= 0:
            raise ValueError("a sweep step must be positive")
        if self.high < self.low:
            raise ValueError("a sweep range must not end below where it starts")

    def values(self) -> tuple[Decimal, ...]:
        """Every point in the range, inclusive of both ends where the step lands.

        Generated by multiplication from the low rather than by repeated
        addition, so the *n*-th value does not depend on the accumulated error
        of the previous *n*, and the same range always produces the same set.
        """
        out: list[Decimal] = []
        step_count = 0
        while (value := self.low + self.step * step_count) <= self.high:
            out.append(value)
            step_count += 1
        return tuple(out)

    @property
    def count(self) -> int:
        """How many values this range contributes. Phase 7's run-count estimate."""
        return len(self.values())


def swept(
    default: object,
    *,
    low: Decimal | float | int | str,
    high: Decimal | float | int | str,
    step: Decimal | float | int | str = 1,
    description: str = "",
) -> Any:
    """A parameter with a declared range, which is what a sweep walks.

    Returns a pydantic ``Field`` whose ``ge``/``le`` enforce the range on every
    construction, and whose ``json_schema_extra`` carries it as data. Both
    halves matter: the constraint means a hand-entered parameter outside the
    range is refused rather than silently run, and the data means Phase 5 does
    not have to reverse-engineer the range out of the JSON schema's keywords.
    """
    bounds = SweepRange(low=money(low), high=money(high), step=money(step), description=description)
    return Field(
        default,
        ge=bounds.low,
        le=bounds.high,
        description=description or None,
        json_schema_extra={
            SWEEP_KEY: {
                "low": str(bounds.low),
                "high": str(bounds.high),
                "step": str(bounds.step),
            }
        },
    )


class Params(BaseModel):
    """The base every strategy's parameter model inherits.

    ``frozen`` because a strategy that edited its own parameters mid-run would
    produce a result no ``param_set`` row describes, and ``extra="forbid"``
    because a typo in a swept parameter name must fail the run rather than
    quietly use the default - a sweep of a misspelled parameter is ten thousand
    identical runs wearing ten thousand different labels.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    @classmethod
    def sweep_space(cls) -> Mapping[str, SweepRange]:
        """Every parameter declared with ``swept()``, and its range.

        Parameters without a declared range are absent: they are configuration
        for the run rather than a dimension to search, and a sweep that walked
        them would be searching over things like which symbol to trade.
        """
        space: dict[str, SweepRange] = {}
        for name, info in cls.model_fields.items():
            bounds = _sweep_of(info)
            if bounds is not None:
                space[name] = bounds
        return space

    @classmethod
    def combinations(cls) -> int:
        """How many parameter sets a full grid over the declared ranges holds."""
        total = 1
        for bounds in cls.sweep_space().values():
            total *= bounds.count
        return total


def _sweep_of(info: FieldInfo) -> SweepRange | None:
    """Read a range back off a field, or ``None`` if it was not declared with one.

    The casts are the price of pydantic typing ``json_schema_extra`` as
    "anything JSON, or a callable that mutates it": the values were written by
    ``swept()`` three functions up, and the ``isinstance`` guards are what makes
    reading them back safe rather than the annotation.
    """
    extra = info.json_schema_extra
    if not isinstance(extra, dict):
        return None
    declared = cast(Mapping[str, object], extra).get(SWEEP_KEY)
    if not isinstance(declared, Mapping):
        return None
    bounds = cast(Mapping[str, object], declared)
    return SweepRange(
        low=Decimal(str(bounds["low"])),
        high=Decimal(str(bounds["high"])),
        step=Decimal(str(bounds["step"])),
        description=info.description or "",
    )


class StrategyContext:
    """Everything a strategy can see, and the only way it can act.

    Constructed fresh by the engine on every tick, holding the cursor for that
    tick. Cheap - it is five references and an integer - and short-lived, which
    is what makes "a strategy cannot stash the context and read it later"
    something the design discourages rather than something a comment asks for.
    """

    __slots__ = ("_broker", "_history", "_index", "_now", "_portfolio")

    def __init__(
        self,
        now: datetime,
        index: int,
        history: BarHistory,
        portfolio: Portfolio,
        broker: Broker,
    ) -> None:
        self._now = now
        self._index = index
        self._history = history
        self._portfolio = portfolio
        self._broker = broker

    # -- what time is it -----------------------------------------------------

    @property
    def now(self) -> datetime:
        """The instant of the bar currently being processed, UTC."""
        return self._now

    @property
    def bar_number(self) -> int:
        """How many bars have been seen, counting this one. 1 on the first."""
        return self._index + 1

    @property
    def is_first_bar(self) -> bool:
        return self._index == 0

    @property
    def is_last_bar(self) -> bool:
        """True on the final bar of the run.

        Knowable in a replay and unknowable live, which is why nothing in the
        shipped strategies uses it to trade. It is here for the honest use -
        a strategy that wants to report at the end - and its presence is the
        reason ``Backtest`` records orders submitted on the last bar as
        expired rather than pretending they filled.
        """
        return self._index == len(self._history) - 1

    # -- what the market did -------------------------------------------------

    @property
    def symbols(self) -> tuple[str, ...]:
        """The universe this run covers, in a stable order."""
        return self._history.symbols

    def bar(self, symbol: str) -> Bar | None:
        """``symbol``'s bar for *this* instant, or ``None`` if it has none."""
        return self._history.bar_at(symbol, self._index)

    def bars(self, symbol: str, count: int | None = None) -> tuple[Bar, ...]:
        """The last ``count`` bars up to and including now. Never further.

        ``None`` means everything so far. A short answer means a short history,
        not an error: a strategy warming up a 200-bar average gets 37 bars on
        the 37th tick and has to notice.
        """
        return self._history.window(symbol, self._index, count)

    def price(self, symbol: str) -> Decimal | None:
        """The most recent close at or before now - what the portfolio is marked at."""
        bar = self._history.latest(symbol, self._index)
        return None if bar is None else money(bar.close)

    def chain(self, underlying: str, expiries: Sequence[date] | None = None) -> pl.DataFrame:
        """The option board for ``underlying`` as of now.

        Declared here and refused here. The plan's two-clock design names
        ``ctx.chain()`` as part of the context a strategy sees either way, so
        the signature belongs in Phase 4 with the rest of the surface; the
        implementation belongs to Phase 10, which is the phase that also
        arrives with the pricing guardrail (``require_priceable_chains``) that
        stops a backtest reading the synthetic source's structurally-valid,
        numerically-meaningless boards. Shipping the method without that
        guardrail would be shipping the confident wrong answer the guardrail
        exists to prevent.
        """
        raise NotImplementedError(
            f"chains are Phase 10; {underlying} boards are collected but not yet backtestable."
            " See docs/plans/trading.md."
        )

    # -- what is held --------------------------------------------------------

    @property
    def portfolio(self) -> Portfolio:
        return self._portfolio

    @property
    def cash(self) -> Decimal:
        return self._portfolio.cash

    @property
    def equity(self) -> Decimal:
        """Cash plus positions at the last mark. What the curve plots."""
        return self._portfolio.equity

    def quantity_of(self, instrument: Instrument, key: str | None = None) -> int:
        """Signed size held, *including orders already queued but not yet filled*.

        Netting the queue in is the point of this method existing rather than
        callers reading the portfolio directly. A strategy that re-evaluates
        its target on every bar and reads only the settled position will submit
        the same entry again on the bar after it signalled - because the first
        order has not filled yet - and end up with twice the intended size.
        That bug is invisible in a rising market.
        """
        held = self._portfolio.quantity_of(instrument, key)
        queued = sum(
            order.quantity
            for order in self._broker.pending
            if order.instrument == instrument and (key is None or order.key == key)
        )
        return held + queued

    # -- acting --------------------------------------------------------------

    def order(
        self,
        instrument: Instrument,
        quantity: int,
        position_key: str | None = None,
        tag: str = "",
    ) -> Order | None:
        """Submit a market order, to fill at the next bar's open.

        ``quantity`` is signed. A quantity of zero is not an error and not an
        order - it is what "rebalance to a target I am already at" evaluates
        to, and making it raise would put a guard clause at every call site.
        """
        if quantity == 0:
            return None
        return self._broker.submit(
            Order(
                instrument=instrument,
                quantity=quantity,
                submitted_at=self._now,
                position_key=position_key,
                tag=tag,
            )
        )

    def order_to_target(
        self,
        instrument: Instrument,
        target: int,
        position_key: str | None = None,
        tag: str = "",
    ) -> Order | None:
        """Order the difference between the target size and what is already committed.

        The form nearly every strategy actually wants: a rule says "be long
        100 shares" or "be flat", and the arithmetic that turns that into a
        delta is the same everywhere and is wrong in the same way everywhere
        when it is written out by hand (see ``quantity_of`` on the queue).
        """
        key = position_key if position_key is not None else position_key_for(instrument)
        return self.order(instrument, target - self.quantity_of(instrument, key), key, tag)


@runtime_checkable
class Strategy(Protocol):
    """One trading rule, holding its validated parameters.

    ``on_bar`` is called once per tick, after fills for that tick have settled
    and after the portfolio has been marked, so a strategy reads a portfolio
    that already reflects what its previous orders did.
    """

    @property
    def params(self) -> Params:
        """The parameters this instance was built from. Frozen; recorded on the run."""
        ...

    def on_bar(self, ctx: StrategyContext) -> None:
        """React to the bar at ``ctx.now``. Orders fill at the next one."""
        ...


@dataclass(frozen=True, slots=True)
class StrategySpec:
    """A strategy as the rest of the system refers to it: a name and a builder.

    ``build`` takes a mapping rather than a ``Params`` instance, and that is
    the shape Phase 5 needs: a ``param_set`` row is JSONB, and the strategy's
    own model is the thing that knows how to validate it. Handing the spec a
    typed model instead would put the "which subclass of ``Params`` does this
    strategy want" question at every call site, answerable only with a cast.
    """

    name: str
    description: str
    params_model: type[Params]
    build: Callable[[Mapping[str, object]], Strategy]

    def sweep_space(self) -> Mapping[str, SweepRange]:
        return self.params_model.sweep_space()

    def default(self) -> Strategy:
        """An instance at every declared default. What a smoke test runs."""
        return self.build({})
