services:
  db:
    image: ghcr.io/eouw0o83hf/aerie-db:latest
    networks:
      - local
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: ghcr.io/eouw0o83hf/aerie-api:${IMAGE_TAG:-latest}
    networks:
      - local
      - edge
    environment:
      - DOTNET_ENVIRONMENT=Docker
    depends_on:
      db:
        condition: service_healthy
    labels:
      caddy: home.${DOMAIN}
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy_1: kiosk.${DOMAIN}
      caddy_1.@root.path: /
      caddy_1.rewrite: "@root /apps/dashboard/"
      caddy_1.reverse_proxy: "{{upstreams 8080}}"

  caddy:
    image: ghcr.io/eouw0o83hf/aerie-caddy:latest
    restart: always
    networks:
      - edge
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    labels:
      caddy.email: ${ACME_EMAIL}
      caddy.acme_dns: route53

networks:
  local:
    driver: bridge
  edge:
    external: true

volumes:
  pgdata:
  caddy_data:
  caddy_config:
