// <auto-generated />
using System;
using Hatch.Api.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hatch.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718005111_parity")]
    partial class parity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hatch.Api.Ef.EfEnvironmentReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DesiredTemperature")
                        .HasColumnType("numeric");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Humidity")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsHeating")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EntityId", "Timestamp" }, "IX_EnvironmentReadings_EntityId_Timestamp")
                        .IsUnique();

                    b.ToTable("EnvironmentReadings");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfZoneConfig", b =>
                {
                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<decimal?>("ComfortHighF")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ComfortLowF")
                        .HasColumnType("numeric");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Included")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("EntityId");

                    b.ToTable("ZoneConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
