// <auto-generated />
using System;
using Hatch.Api.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hatch.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818234410_AddRoutineIsToggle")]
    partial class AddRoutineIsToggle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hatch.Api.Ef.EfCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfirmedValue")
                        .HasColumnType("text");

                    b.Property<Guid?>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("OverriddenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.HasIndex("ChannelId", "RequestedAt");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfControlDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChosenActionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InputsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("RunnerUpJson")
                        .HasColumnType("text");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("ControlDecisions");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfControlOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExpectedState")
                        .HasColumnType("text");

                    b.Property<string>("ObservedState")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SuppressedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CommandId");

                    b.HasIndex("DeviceId", "SuppressedUntil");

                    b.ToTable("ControlOverrides");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("HaDeviceId")
                        .HasColumnType("text");

                    b.Property<int?>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfDeviceChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvailableOptions")
                        .HasColumnType("text");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("HaAttribute")
                        .HasColumnType("text");

                    b.Property<string>("HaEntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Metric")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceChannels");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfEnvironmentReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DesiredTemperature")
                        .HasColumnType("numeric");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Humidity")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsHeating")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EntityId", "Timestamp" }, "IX_EnvironmentReadings_EntityId_Timestamp")
                        .IsUnique();

                    b.ToTable("EnvironmentReadings");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChannelId", "Timestamp" }, "IX_Measurements_ChannelId_Timestamp")
                        .IsUnique();

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfRoutine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("Included")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsToggle")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Routines");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfRoutineAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("RoutineId");

                    b.ToTable("RoutineActions");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfSiteSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfStateChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChannelId", "Timestamp" }, "IX_StateChanges_ChannelId_Timestamp")
                        .IsUnique();

                    b.ToTable("StateChanges");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ComfortHighF")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ComfortLowF")
                        .HasColumnType("numeric");

                    b.Property<bool>("Included")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfZoneConfig", b =>
                {
                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<decimal?>("ComfortHighF")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ComfortLowF")
                        .HasColumnType("numeric");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Included")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("EntityId");

                    b.ToTable("ZoneConfigs");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfCommand", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfDeviceChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hatch.Api.Ef.EfControlDecision", "Decision")
                        .WithMany("Commands")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Channel");

                    b.Navigation("Decision");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfControlOverride", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfDeviceChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hatch.Api.Ef.EfCommand", "Command")
                        .WithMany()
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hatch.Api.Ef.EfDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Command");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfDevice", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfZone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfDeviceChannel", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfDevice", "Device")
                        .WithMany("Channels")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfMeasurement", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfDeviceChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfRoutineAction", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfDeviceChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hatch.Api.Ef.EfRoutine", "Routine")
                        .WithMany("Actions")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfStateChange", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfDeviceChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfControlDecision", b =>
                {
                    b.Navigation("Commands");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfDevice", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfRoutine", b =>
                {
                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
