[SERVICE]
    Flush         5
    Daemon        off
    Log_Level     info
    Parsers_File  parsers.conf

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Tag               docker.*
    Refresh_Interval  5
    Mem_Buf_Limit     10MB
    Skip_Long_Lines   On

[OUTPUT]
    Name            opensearch
    Match           docker.*
    Host            opensearch
    Port            9200
    Index           aerie-logs
    Logstash_Format On
    Logstash_Prefix aerie-logs
    tls             Off
    Suppress_Type_Name On
