import { chunk, geometryFor } from './labelLayout';
import type { LabelLayout } from './labelLayout';
import { crateLabelUrl } from './routes';
import type { Crate } from './types';

/**
 * The printable sheet: pages of QR + printed code + a line to write on.
 *
 * Pure presentation - the QR images are generated by the caller (see qr.ts), so
 * this renders nothing asynchronously and a print dialog opened over it is
 * never racing an empty <img>.
 *
 * On screen it is a preview at true physical size, because it's built out of
 * `mm`: what you see is what comes out, which is the only way to judge whether
 * a QR is big enough before spending a sheet of paper - or a sheet of stickers -
 * on it.
 *
 * Every measurement comes from the geometry, including the ones that used to be
 * constants here: on plain paper they're a preference, but on a die-cut stock
 * they're where the die is, and the two have to be described by the same code
 * for the preview to stay honest about both.
 */
export function LabelSheet({
  crates,
  layout,
  baseUrl,
  images,
}: {
  crates: Crate[];
  layout: LabelLayout;
  baseUrl: string;
  images: Record<string, string>;
}) {
  const geometry = geometryFor(layout);
  const { stock } = geometry;
  const pages = chunk(crates, geometry.perPage);

  return (
    <div className="label-sheet">
      {/* The one thing that has to reach the print engine rather than an
          element: page size and margins are properties of the paper, and
          @page is the only way to say so. On a die-cut stock this is what
          lands the grid on the die, so it is not decoration. */}
      <style>
        {`@page { size: ${geometry.page.id}; margin: ${stock.marginYMm}mm ${stock.marginXMm}mm; }`}
      </style>

      {pages.map((page) => (
        <div
          key={page[0].id}
          className="label-page"
          style={{
            width: `${geometry.contentWidthMm}mm`,
            height: `${geometry.contentHeightMm}mm`,
            // 1fr rather than the computed cell width: the two agree to the
            // millimetre, and fr can't round its way into an overflow that
            // costs a blank page.
            gridTemplateColumns: `repeat(${geometry.columns}, 1fr)`,
            gridTemplateRows: `repeat(${geometry.rows}, 1fr)`,
            gap: `${stock.gapYMm}mm ${stock.gapXMm}mm`,
          }}
        >
          {page.map((crate) => (
            <div
              key={crate.id}
              className={[
                'label-cell',
                geometry.stacked ? 'stacked' : '',
                stock.cutLines ? 'cut' : 'die-cut',
              ]
                .filter(Boolean)
                .join(' ')}
              style={{
                padding: `${stock.padMm}mm`,
                gap: `${stock.padMm}mm`,
                borderRadius: stock.cornerRadiusMm ? `${stock.cornerRadiusMm}mm` : undefined,
              }}
            >
              <img
                className="label-qr"
                src={images[crateLabelUrl(baseUrl, crate.code)]}
                alt=""
                style={{ width: `${geometry.qrMm}mm`, height: `${geometry.qrMm}mm` }}
              />
              <div className="label-text">
                <div className="label-code" style={{ fontSize: `${geometry.codeMm}mm` }}>
                  {crate.displayCode}
                </div>
                {/* A crate that already has a name prints it; a blank one gets a
                    line, because the name is written on with a marker at the
                    moment the box is filled - that's the whole workflow. */}
                {crate.label ? (
                  <div className="label-name" style={{ fontSize: `${geometry.codeMm * 0.75}mm` }}>
                    {crate.label}
                  </div>
                ) : (
                  <div className="label-write-on" style={{ height: `${geometry.codeMm * 1.4}mm` }} />
                )}
              </div>
            </div>
          ))}
        </div>
      ))}
    </div>
  );
}
