"""The Ledger's floor: instrument, data_source, ingest_run.

The first migration, and deliberately the whole of Phase 1's schema - nothing
about strategies, runs or metrics, which are Phase 5 and should be written by
the phase that knows what it needs from them.

Hand-written rather than autogenerated. Autogenerate is the right tool once
there is a database to diff against; for the first revision it produces the
same DDL with a comment header claiming it was derived from a comparison that
never happened. ``tests/test_migrations.py`` asserts this file and
``aerie_trading/db/models.py`` still describe the same schema, which is the
check autogenerate would have been standing in for.

Revision ID: 0001_ledger_floor
Revises:
Create Date: 2026-09-02
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_ledger_floor"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # data_source first: ingest_run's foreign key names it, and a migration
    # that creates tables in the wrong order fails on the constraint rather
    # than on anything that says "order".
    op.create_table(
        "data_source",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_source")),
        sa.UniqueConstraint("name", name=op.f("uq_data_source_name")),
    )

    op.create_table(
        "instrument",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("underlying_symbol", sa.String(length=32), nullable=True),
        sa.Column("expiry", sa.Date(), nullable=True),
        sa.Column("strike", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("option_right", sa.String(length=8), nullable=True),
        sa.Column("multiplier", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('equity', 'option')", name=op.f("ck_instrument_kind")),
        sa.CheckConstraint(
            "option_right IS NULL OR option_right IN ('call', 'put')",
            name=op.f("ck_instrument_right"),
        ),
        sa.CheckConstraint(
            "(kind = 'option') = (underlying_symbol IS NOT NULL"
            " AND expiry IS NOT NULL AND strike IS NOT NULL"
            " AND option_right IS NOT NULL)",
            name=op.f("ck_instrument_option_fields"),
        ),
        sa.CheckConstraint("multiplier > 0", name=op.f("ck_instrument_multiplier")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instrument")),
        sa.UniqueConstraint("symbol", name=op.f("uq_instrument_symbol")),
    )
    op.create_index(
        "ix_instrument_underlying_expiry",
        "instrument",
        ["underlying_symbol", "expiry"],
    )

    op.create_table(
        "ingest_run",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("data_source_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("request", postgresql.JSONB(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("rows_written", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("quota_cost", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("aerie_revision", sa.String(length=40), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed')",
            name=op.f("ck_ingest_run_status"),
        ),
        sa.CheckConstraint("rows_written >= 0", name=op.f("ck_ingest_run_rows_written")),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_source.id"],
            name=op.f("fk_ingest_run_data_source_id_data_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_run")),
    )
    op.create_index(
        "ix_ingest_run_source_kind_started",
        "ingest_run",
        ["data_source_id", "kind", "started_at"],
    )


def downgrade() -> None:
    # Reverse order, for the same foreign key reason the upgrade has an order
    # at all. Written rather than left as `pass`: a migration with no
    # downgrade is one that cannot be rehearsed, and rehearsing it on an empty
    # database is the only time it is free.
    op.drop_index("ix_ingest_run_source_kind_started", table_name="ingest_run")
    op.drop_table("ingest_run")
    op.drop_index("ix_instrument_underlying_expiry", table_name="instrument")
    op.drop_table("instrument")
    op.drop_table("data_source")
